=== dihedron/dihedron-webmvc/dihedron-webmvc/src/main/resources/org/dihedron/webmvc/interceptors/interceptors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2012-2015, Andrea Funto' - All rights reserved. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="stack">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="interceptors" />
				<xs:element ref="results" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:normalizedString" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="result">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:normalizedString">
					<xs:attribute name="value" type="xs:normalizedString"
						use="required" />
					<xs:attribute name="renderer" type="xs:normalizedString"
						use="optional" default="jsp" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="results">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="result" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:normalizedString">
					<xs:attribute name="key" type="xs:normalizedString"
						use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="interceptor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:normalizedString" use="required" />
			<xs:attribute name="class" type="xs:normalizedString"
				use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="interceptors">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="interceptor" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="stack" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dihedron/dihedron-webmvc/dihedron-webmvc/src/main/resources/org/dihedron/webmvc/default-interceptors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2012-2015, Andrea Funto' - All rights reserved. -->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="interceptors.xsd">
	<stack id="default">
		<interceptors>
			<interceptor id="profiler" class="org.dihedron.webmvc.interceptors.impl.Profiler"/>
			<interceptor id="dumper" class="org.dihedron.webmvc.interceptors.impl.Dumper">		 
				<parameter key="exclude">\s*org\.apache\.tomcat\.util\.scan\.MergedWebXml\s*</parameter>
				<!-- 
				<parameter key="exclude">^[A-Z_]*$|^org\.apache.*|^javax\.servlet.*|^org\.dihedron\.webmvc.*|^j_.*</parameter>
				-->			
				<parameter key="scopes">form,request,conversation,session,sticky,application</parameter>			
			</interceptor>
		<!-- 
			<interceptor id="double-submit" class="org.dihedron.strutlets.interceptors.impl.Resubmit">
				<parameter key="result">error_double_submit</parameter>			
			</interceptor>
		-->
		</interceptors>
		<results>
			<result value="uncaught_exception" renderer="jsp">internal_error.jsp</result>
		</results>
	</stack>
</configuration>
